### ISSUE TITLE
AllYourTexts bug

### ISSUE THREAD

**Issue by ghost** [AllYourTexts/AllYourTexts#10]
Hey, hopefully you can help me out! I downloaded the software a while ago, I ended up liking it so I bought it. However, as of late it CONSTANTLY crashes whenever I open a specific conversation. The only difference between this conversation and others is that it is the longest, so I'm guessing that the length of it is the problem. Please let me know if there is any fix for this, as I have been really pleased with the software until now. It crashes every time I open that one convo.

**Comment by ghost** [comment]
It has been 2 weeks and I still waiting for someone to assist me.

**Comment by AllYourTexts** [comment]
Can you send an email to support@allyourtexts.com and we can try to diagnose the cause of the issue?
